services:
  duck-database:
    image: postgres:alpine
    container_name: duck-database
    ports:
      - "6001:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spring-2024